---
title: "Plotting"
author: "Andreas M. Brandmaier"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Plotting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(1168385)
```


```{r}
library(pdcsync)

N <- 1000

t1 <- arima.sim(model = list(ar = 0.2), n = N)
t2 <- arima.sim(model = list(ar = 0.2), n = N)

t2[500:700] <- t1[500:700+10]

t1[1:300] <- t2[1:300+3]
```

```{r}
result <- pdcsync(t1, t2, segment_width = 100, search_width = 5)
```

Plot the simple synchronisation profile
```{r}
plot(result)
```

Suppress the best-fitting synchronisation line:
```{r p3, warning=FALSE}
plot(result, show_sync_line = FALSE)
```

Show the line again and vary output:
```{r p4, warning=FALSE}
plot(result, show_sync_line = TRUE, sync_lwd=1, sync_col="green")
```

Plot the extended synchronisation profile including the time series.
```{r p5, warning=FALSE}
syncplot(result)
```

Annotate segments that are "leading" segments with green areas:

```{r p6, warning=FALSE}
syncplot(result, annotate_segments = TRUE)
```